// <auto-generated />
namespace ASP.NET_ECOMMERCE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RefactoringControllers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefactoringControllers));
        
        string IMigrationMetadata.Id
        {
            get { return "201706031024104_Refactoring Controllers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
